### PR TITLE
Add JSON Editor

### PR DESCRIPTION
**Pull request by CSLTech**
Add JSON Editor component plugin that brings a better, more fully featured JSON editor to Budibase.

### CODE REVIEW

**Comment by ConorWebb96** [comment]
Hey @CSLTech,

The plugin doesn't seem to work with forms that are setup to get data back?

When I tried to integrate it, it just shows up as if it were a create form field. 
Screenshot 2024-03-12 at 15 45 13
Screenshot 2024-03-12 at 15 45 29
Screenshot 2024-03-12 at 15 46 43

I think before it can be merged in, it would need to be able to handle information via edit forms.

I hope this makes sense.

If you think I've not set it up properly please let me know. I've flicked through the variable tabs; json, tree and table and it doesn't seem to have the pre-populated JSON values inside it.

**Comment by CSLTech** [comment]
@ConorWebb96 This wasn't one of our use cases, but I will certainly take a look. Thank you for the feedback.

**Comment by CSLTech** [comment]
@ConorWebb96 This should now be fixed in 1.1.2 :slightly_smiling_face:

**Review by ConorWebb96 — APPROVED** [review]
Looks good now, thank you for fixing that!

**Pull request merged**
