### PR TITLE
Calendar component

### PR DESCRIPTION
**Pull request by marblekirby**
Check out my repo with the calendar integration: https://github.com/marblekirby/budibase-calendar-plugin

## Features
- Can be used to represent information by date
- Works with any data provider, just provide a mapping for the date field and title field of calendar

## Limitations
- Only for "all day" events - no time shown on calendar
- Further customisation of events required (although likely I'll do this tomorrow) 

Small video of component in a budibase application
2022-10-23_02h26_41

### CODE REVIEW

**Comment by melohagan** [comment]
Hey @marblekirby 

This looks really cool! I did notice a bug though, if you change the month or year, the event pills remain in place:

Screenshot 2022-10-24 at 08 44 00

calendar

**Comment by marblekirby** [comment]
Thank you for letting me know. Looks like I have pushed _work in progress_ code to my repo, I'll fix that issue today. 

I'm also adding support for displaying event times, and customisations.

**Comment by marblekirby** [comment]
Updates made to include 
- Time of events
- Some styling although not all of theme integrated
- All day events vs time events

todo
- Continue to integrate themeing 
- Multi day events
- Limit number of shown events

I'll continue to maintain this component outside of the hackathon, thanks 👍 

image

**Review by melohagan — APPROVED** [review]
Nice one, this looks fantastic! 📆 🚀 

One tiny thing is that you can add an icon into the schema. Spectrum actually has a number of Calendar icons to choose from: https://spectrum.adobe.com/page/icons/

Otherwise great work :)

**Pull request merged**
