### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ConorWebb96**
Updated readme to include the new type a head input field component.

### CODE REVIEW

**Review by melohagan — COMMENTED** [review]
Should it be `Type Ahead` ?

**Comment by andz-bb** [comment]
>A component used for to querying tables

can get rid of the `to` here

**Comment by ConorWebb96** [comment]
@melohagan @andz-bb fixed both 👍

**Comment by diogenesbrussels** [comment]
perhaps add the term 'searchable option picker' somewhere because the function is similar to the existing component?

the alphabetical order is also bit messed up with this commit 😄

**Pull request merged**
