### PR TITLE
Adding countdown timer

### PR DESCRIPTION
**Pull request by JayP718**
Adding a countdown which counts down (days/min/secs) to a certain date time.

### CODE REVIEW

**Comment by melohagan** [comment]
Hey @JayP718 

We've been having issues getting your component to display unfortunately 🤕 

Screenshot 2022-10-19 at 08 39 49

The code and schema looks fine to me!

What I'm thinking is if you could ensure you have the latest version of the CLI installed: https://docs.budibase.com/docs/budibase-cli-setup
Then run your `init --component`. Copy over the `schema.json` and `Component.svelte` files from the old project into the new one. Make sure that works on your end and then push the new codebase up to another repo.

**Comment by andz-bb** [comment]
hey @JayP718, thanks for your contribution! I got the component working, there was just a minor mismatch in component names between schema.json and package.json. I made a PR with a fix for it here: https://github.com/JayP718/Countdown_Timer/pull/1

cc: @melohagan can you test this updated version on your end please?

**Comment by JayP718** [comment]
Thanks @andz-bb  sorry about that it was working on my end, I'll keep an eye out on that in the future. I just merged that pull requests, thanks for having a look.

**Comment by melohagan** [comment]
Thanks for that @andz-bb !

@JayP718 That's working now - thanks very much for your contribution!

I found it to be quite difficult to figure out how to set it up. I would probably show a screenshot of the component tree in your readme, 
i.e.
> Data Provider
> > Repeater
> > > Form
> > > > Time field (with Date value)

**Review by melohagan — APPROVED** [review]
LGTM! 👍

**Comment by JayP718** [comment]
@melohagan Thanks for the feedback! added!

**Pull request merged**
