### PR TITLE
Add Auto-Complete Field

### PR DESCRIPTION
**Pull request by CSLTech**

### CODE REVIEW

**Comment by ConorWebb96** [comment]
Hey @CSLTech,

There seems to be a lot of issues with this plugin.

- The label and value field names don't seem to do anything
- Data source filter appears to be broken, fires off constant errors in the console when trying to search
Screenshot 2024-03-27 at 08 44 40
Screenshot 2024-03-27 at 08 44 54
- The query option instantly breaks the component
Screenshot 2024-03-27 at 08 42 56
- I'm not quite sure how the api source is meant to be setup for it to work, I haven't had a play around with this yet.
- Static seems to be the only one i've tested so far that works properly.


Overall a lot of fixes likely need to be done here before it can be merged. 👍

**Comment by CSLTech** [comment]
I have just pushed fixes for the bugs just mentioned. The value and label fields are meant to be configured to fields within the objects returned by the datasource/query/api to select labels and values.

The Query mode does require a bit more configuration as mentioned in the README.

As for the API mode, it's meant to call an external API directly, from the browser.

**Comment by CSLTech** [comment]
@ConorWebb96 Just following up on this. Did you get a chance to look at the updated version?

**Comment by ConorWebb96** [comment]
Hey @CSLTech,

Thank you for fixing the other bugs.

- Budibase datasource ✅ 
- Static ✅ 
- API ✅ 
- query ✅

**Pull request merged**
